apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ha-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/toyinogun/web-app.git
    targetRevision: HEAD
    path: nginx-ha-chart
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-apps
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true